### ISSUE TITLE
npm install and npm start not idempotent?

### ISSUE THREAD

**Issue by rreusser** [stackgl/packages#17]
It seems like building or starting the server fails if I don't `rm -rf dist` before installing or starting (except for the package data json; I can keep that). It's possible this is my scijs specialization, but I don't think I've changed anything substantial there. Is it possible it just fails if `cpr` is asked to overwrite files?

```
/Users/rreusser/projects/node/scijs/packages/build-make.js:13
  if (err) throw err
           ^

Error: Unable to copy directory entirely
  at /Users/rreusser/projects/node/scijs/packages/node_modules/cpr/lib/index.js:274:39
  at check (/Users/rreusser/projects/node/scijs/packages/node_modules/cpr/lib/index.js:169:17)
  at copy (/Users/rreusser/projects/node/scijs/packages/node_modules/cpr/lib/index.js:177:24)
  at doNTCallback0 (node.js:419:9)
  at process._tickCallback (node.js:348:13)
```

**Comment by hughsk** [comment]
Ah strange! Only seems to be an issue with a more recent version of `cpr` to what I had installed — keeping it at exactly `0.4.1` seems to do the trick though: https://github.com/stackgl/packages/commit/e14f706723407ecb3ca94a48eac40b5ed4df4805 Let me know if that fixes it for you?

**Comment by rreusser** [comment]
Yup, that fixed it just fine. Note to self: check if default [`overwrite` option](https://github.com/davglass/cpr#usage) behavior changed, i.e. if setting that flag explicitly fixes it with the new version.

**Comment by kevzettler** [comment]
can this be closed?
