### ISSUE TITLE
`npm i` is broken with node v10

### ISSUE THREAD

**Issue by nkint** [stackgl/packages#20]
Hi!
I'm tring to build this project locally but both `npm i` both `yarn` stops when trying to run gyp and c++ code.
I think the problem is in `leveldown`:
```Failed at the leveldown@1.7.2 install script.```

Is there a way to resolve this problem?
Maybe installing an older node version?

In particular I'm interesting into use all this for an ecosystem I have in mind and I will skip all the json building starting from a wiki as done in `stack.gl`.

Thanks guys! This is a super cool project!

**Comment by kevzettler** [comment]
try using installing with the locked file versions from package-lock
